name: macropac_rastreamento
description: Macropac Rastreamento - V8 com segundo plano nativo Android.
publish_to: "none"
version: 1.0.8+8

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  battery_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
