name: macropac_rastreamento

description: Aplicativo Macropac Rastreamento de Frota
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  geolocator: ^13.0.1
  battery_plus: ^6.0.3
  device_info_plus: ^10.1.2
  wakelock_plus: ^1.2.8

flutter:
  uses-material-design: true
